feature: ['feat/*', 'feature/*']
enhancement: ['enhance/*', 'enhancement/*']
fix: ['fix/*', 'bug/*', 'bugfix/*', 'hotfix/*']
changes: ['change/*', 'changes/*', 'changed/*']
performance: ['perf/*', 'performance/*']
refactor: ['refactor/*']
devops: ['build/*', 'ops/*', 'devops/*']
deprecates: ['deprecate/*', 'deprecates/*', 'deprecated/*']
removes: ['remove/*', 'removes/*', 'removed/*', 'delete/*', 'deletes/*', 'deleted/*']
security: ['secure/*', 'secures/*', 'secured/*', 'security/*']
documentation: ['docs/*', 'documentation/*']
dependencies: ['deps/*', 'dependencies/*']
chore: ['chore/*']
style: ['style/*']
