# This release drafter follows the conventions
# from https://keepachangelog.com

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  # labels should include values of .github/pr-labeler.yaml
  - title: 🚀 Added
    labels:
      - feature
      - enhancement
  - title: 🪲 Fixed
    labels:
      - fix
  - title: ⚠️ Changed
    labels:
      - changes
      - performance
      - devops
      - test
  - title: ⛔️ Deprecated
    labels:
      - deprecates
  - title: 🗑 Removed
    labels:
      - removes
  - title: 🔐 Security
    labels:
      - security
  - title: 📓 Documentation
    labels:
      - docs
  - title: 🧩 Updated
    labels:
      - dependencies
    collapse-after: 5

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

exclude-labels:
  - style
  - chore
