plugins:


  postcss-import:
    path:
      - './source'


  postcss-extend: {}


  # https://github.com/TACC/Core-CMS/blob/70a1ca3/conf/css/.postcssrc.yml#L6-L12
  postcss-env-function:
    importFrom:
      - './source/_themes/export.js'


  postcss-preset-env:

    # https://github.com/csstools/postcss-preset-env#features
    stage: false

    # https://github.com/csstools/postcss-preset-env/blob/master/src/lib/plugins-by-id.js#L35
    features:
      custom-media-queries: true
      media-query-ranges: true


  cssnano:
    preset:
      - 'default'
      -
        # Both of these are disabled to allow manual CSS build tests
        # The `discardDuplicates` is disabled to prevent hiding duplicate CSS
        discardDuplicates:
          exclude: true
        mergeRules:
          exclude: true
