plugins:
  postcss-import: {}

  postcss-extend: {}

  # https://github.com/TACC/Core-CMS/blob/70a1ca3/conf/css/.postcssrc.yml#L6-L12
  postcss-env-function:
    importFrom:
      - 'src/lib/_themes/default.json'

  postcss-preset-env:
    # https://github.com/csstools/postcss-preset-env#features
    stage: false

    # https://github.com/csstools/postcss-preset-env/blob/master/src/lib/plugins-by-id.js#L35
    features:
      custom-media-queries: true
      media-query-ranges: true
      custom-selectors: true
      # This feature (to come in v8) is not ready yet
      # https://github.com/csstools/postcss-plugins/issues/481#issuecomment-1335678359
      cascade-layers: false

  cssnano:
    preset:
      - 'default'
      - # Both of these are disabled to allow manual CSS build tests
        # The `discardDuplicates` is disabled to prevent hiding duplicate CSS
        discardDuplicates:
          exclude: true
        mergeRules:
          exclude: true

  postcss-banner:
    banner: 'no build id'
    inline: true
    important: true

  postcss-replace:
    # @tacc/core-styles 'demo/' expects `./fonts`, but src uses `../../fonts`
    pattern: ../../fonts/
    data:
      # FAQ: Do not prepend './', cuz downstream postcss-import will strip it
      # FAQ: A string matching any final output simplifies downstream testing
      replaceAll: fonts/
