plugins:
  postcss-import:
    path:
      - 'src/lib'

  postcss-extend: {}

  postcss-preset-env:
    # https://github.com/csstools/postcss-preset-env#features
    stage: false

    # https://github.com/csstools/postcss-preset-env/blob/master/src/lib/plugins-by-id.js#L35
    features:
      custom-media-queries: true
      media-query-ranges: true
      # RFE: Fix bug on the Internet so we can use these reliably
      # SEE: https://github.com/postcss/postcss-custom-selectors/issues/40
      custom-selectors: true

  cssnano:
    preset:
      - 'default'
      - # Both of these are disabled to allow manual CSS build tests
        # The `discardDuplicates` is disabled to prevent hiding duplicate CSS
        discardDuplicates:
          exclude: true
        mergeRules:
          exclude: true

  postcss-banner:
    banner: 'no build id'
    inline: true
    important: true
