# Do not let built-in-place files be comitted to `main` branch
name: Lint
on: [push]
# on:
#   push:
#     branches:
#       - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Lint directories
        run: npm run lint:dirs
