# To assign labels when PR is opened
# FAQ: This simple wrapper exists because original author failed other solutions
name: PR Label Asssigner Manager (on Open)
on:
  pull_request:
    types:
      - opened
      - reopened # for testing

jobs:
  assign_label:
    name: Assign
    uses: ./.github/workflows/pr-label-assigner.yaml

  check_labels_after_assign:
    needs: [assign_label]
    name: Check
    uses: ./.github/workflows/pr-label-checker.yaml
