# To check labels when they are added or removed
# FAQ: This simple wrapper exists to mirror pr-label-assigner-manager.yaml
name: PR Label Checker Manager (on Label)
on:
  pull_request:
    types:
      - labeled
      - unlabeled # for testing

jobs:
  check_labels:
    name: Check
    uses: ./.github/workflows/pr-label-checker.yaml
