# To isolate complexity of PR label task conditional dependency
name: PR Label Manager (on Open, Assign then Check)
on:
  pull_request:
    types:
      - opened
      - reopened # for testing

jobs:
  assign_label:
    name: Assign
    uses: ./.github/workflows/pr-label-assigner.yaml

  check_labels_after_assign:
    needs: [assign_label]
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Check Labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pr-label-checker.yaml',
              ref: '${{ github.head_ref }}'
            })
