# Check whether labels meet expectations
name: PR Label Checker
on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  check_semver_labels:
    name: Check for Semver Label
    runs-on: ubuntu-latest

    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: major,minor,patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  check_cc_labels:
    name: Check for Conventional Commits Label
    runs-on: ubuntu-latest

    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: feature,enhancement,fix,changes,performance,devops,test,deprecates,removes,security,documentation,dependencies,chore,style # should match keys of .github/pr-labeler.yaml
          githubToken: ${{ secrets.GITHUB_TOKEN }}
