# To isolate complexity of PR label task conidtional dependentency
name: PR Label Manager
on:
  pull_request:
    types:
      - opened
      - reopened # for testing
      - labeled
      - unlabeled

jobs:
  assign_labels:
    if: |
      github.event.pull_request.type == 'opened' ||
      github.event.pull_request.type == 'reopened'
    name: (On PR Open) Use "PR Label Assigner"
    uses: ./.github/workflows/pr-label-assigner.yaml

  check_labels_after_assign:
    needs: [assign_labels]
    name: (After Label Assign) Trigger "PR Label Assigner"
    runs-on: ubuntu-latest

    steps:
      - name: Trigger PR Label Checker
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pr-label-checker.yaml',
              ref: '${{ github.head_ref }}'
            })

  check_labels:
    if: |
      always() && (
        github.event.pull_request.type == 'labeled' ||
        github.event.pull_request.type == 'unlabeled'
      )
    name: (On Label Change) Use "PR Label Assigner"
    uses: ./.github/workflows/pr-label-checker.yaml
