name: PR Label Manager (on Open)
on:
  pull_request:
    types:
      - opened
      - reopened # for testing

jobs:
  pr_labeler:
    uses: ./.github/workflows/pr-labeler.yaml

  check_labels:
    needs: [pr_labeler]
    uses: ./.github/workflows/pr-label-checker.yaml
