name: PR Label Checker

on:
  workflow_run:
    workflows: [PR Labeler]
    types:
      - completed
  pull_request:
    types:
      - labeled
      - unlabeled
  push:
    paths:
      - .github/pr-label-checker.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check_semver_labels:
    name: Check for Semver Label
    # HELP: Should this conditional be so complex?
    if: >-
      ${{
        (
          github.event.workflow_run &&
          github.event.workflow_run.conclusion == 'success'
        ) ||
        github.event.pull_request ||
        github.event.push
      }}
    runs-on: ubuntu-latest

    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: major,minor,patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  check_cc_labels:
    name: Check for Conventional Commits Label
    # HELP: Should this conditional be so complex?
    if: >-
      ${{
        (
          github.event.workflow_run &&
          github.event.workflow_run.conclusion == 'success'
        ) ||
        github.event.pull_request ||
        github.event.push
      }}
    runs-on: ubuntu-latest

    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: feature,enhancement,fix,changes,performance,devops,test,deprecates,removes,security,documentation,dependencies,chore,style # should match keys of .github/pr-labeler.yaml
          githubToken: ${{ secrets.GITHUB_TOKEN }}
