# To isolate complexity of PR label task conditional dependency
name: PR Label Checker Manager (on Label)
on:
  pull_request:
    types:
      - labeled
      - unlabeled # for testing

jobs:
  check_labels:
    name: Check
    uses: ./.github/workflows/pr-label-checker.yaml
