name: PR Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check_semver_labels:
    name: Check Semver Label is Used
    runs-on: ubuntu-latest

    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: major,minor,patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  check_cc_labels:
    name: Check Conventional Commits Label is Used
    runs-on: ubuntu-latest

    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: feature,enhancement,fix,changes,performance,devops,test,deprecates,removes,security,docs,dependencies # should match keys of .github/pr-labeler.yaml
          githubToken: ${{ secrets.GITHUB_TOKEN }}
