# To isolate complexity of PR label task conditional dependency
name: PR Label Manager (on Label, Check)
on:
  pull_request:
    types:
      - labeled
      - unlabeled # for testing

jobs:
  check_labels:
    name: (On PR Label) Use "PR Label Checker"
    uses: ./.github/workflows/pr-label-checker.yaml
