# To isolate complexity of PR label task conidtional dependentency
name: PR Label Manager
on:
  pull_request:
    types:
      - opened
      - reopened # for testing

jobs:
  assign_labels:
    name: Use "PR Label Assigner"
    uses: ./.github/workflows/pr-label-assigner.yaml

  trigger_check_labels:
    needs: [assign_labels]
    name: Trigger "PR Label Checker"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PR Label Checker
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pr-label-checker.yaml',
              ref: '${{ github.head_ref }}'
            })